<?php

namespace JMS\Payment\CoreBundle\PluginController;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EntityPluginController__JMSInjector
{
    public static function inject($container) {
        $instance = new \JMS\Payment\CoreBundle\PluginController\EntityPluginController();
        return $instance;
    }
}
