sportimimi_admin_homepage:
    pattern:  /
    defaults: { _controller: SportimimiAdminBundle:Dashboard:index }

sportmimi_admin_users:
    prefix: /users
    resource: "@SportimimiAdminBundle/Resources/config/routing/users.yml"

sportmimi_admin_news:
    prefix: /news
    resource: "@SportimimiAdminBundle/Resources/config/routing/news.yml"

sportmimi_admin_client:
    prefix: /clients
    resource: "@SportimimiAdminBundle/Resources/config/routing/clients.yml"

sportmimi_admin_place:
    prefix: /places
    resource: "@SportimimiAdminBundle/Resources/config/routing/places.yml"