parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: teamsport
    database_user: root
    database_password: "Kdz-ZvQG$(#fg:"
    mailer_transport: smtp
    mailer_host: in-v3.mailjet.com
    mailer_user: cc9d88d0aed08b28d146d1723ecce4ec
    mailer_password: b06d2edd9af5f7474305e58b1bba9f16
    locale: vi
    secret: a4b83ee5213a38272ef4645561aba4d18ce8eebb
    database_path: null
    api_facebook_id:      1414230258790226 
    api_facebook_secret:  538117b0bf7ebef94ace1a137d348555
    api_facebook_name:    http://apps.facebook.com/teamsportvn/
    api_facebook_server:  http://teamsport.vn/