jms_security_extra:
    secure_all_services: false
    expressions: true

#FOSUserBundle 
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
 
    providers:
        #my_fos_facebook_provider:
            #id: my.facebook.user  
        fos_userbundle:
            id: fos_user.user_provider.username_email     
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|assets)/
            security: false
        api:
            pattern: ^/api/.*
            fos_oauth: true
            stateless: true
            anonymous:  true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        # defaut login area for standard users
        main:
            pattern:      ^/
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_registration_register
                check_path:     fos_user_security_check
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                    yahoo: "/login/check-yahoo"
                login_path:     fos_user_registration_register
#                failure_path: hwi_oauth_connect
                oauth_user_provider:
                    service: sportimimi_oauth_provider
            logout:
                path:           /logout
                invalidate_session: false
            anonymous:    ~

    access_control:
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dang-nhap, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/dang-nhap, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^en/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ve-chung-toi, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/ve-chung-toi, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/map/nguoi-dang-choi, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/map/nguoi-dang-choi, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/map/fields, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/map/fields, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/markers-field, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/markers-field, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/markers, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/markers, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usersOnline, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/usersOnline, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs

        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
