sportmimi_admin_news_index:
    pattern: /
    defaults: { _controller: teamsport.admin_controller.news:indexAction }

sportmimi_admin_news_new:
    pattern: /new
    defaults: { _controller: teamsport.admin_controller.news:newAction }

sportmimi_admin_news_show:
    pattern: /{id}/show
    defaults: { _controller: teamsport.admin_controller.news:showAction }

sportmimi_admin_news_edit:
    pattern: /{id}/edit
    defaults: { _controller: teamsport.admin_controller.news:editAction }

sportmimi_admin_news_delete:
    pattern: /{id}/delete
    defaults: { _controller: teamsport.admin_controller.news:deleteAction }
