sportmimi_admin_place_index:
    pattern: /
    defaults: { _controller: teamsport.admin_controller.place:indexAction }

sportmimi_admin_place_new:
    pattern: /new
    defaults: { _controller: teamsport.admin_controller.place:newAction }
    
sportmimi_admin_place_show:
    pattern: /{id}/show
    defaults: { _controller: teamsport.admin_controller.place:showAction }

sportmimi_admin_place_edit:
    pattern: /{id}/edit
    defaults: { _controller: teamsport.admin_controller.place:editAction }

sportmimi_admin_place_delete:
    pattern: /{id}/delete
    defaults: { _controller: teamsport.admin_controller.place:deleteAction }
