sportmimi_admin_users_index:
    pattern: /
    defaults: { _controller: teamsport.admin_controller.users:indexAction }

sportmimi_admin_user_show:
    pattern: /{id}/show
    defaults: { _controller: teamsport.admin_controller.users:showAction }

sportmimi_admin_users_edit:
    pattern: /{id}/edit
    defaults: { _controller: teamsport.admin_controller.users:editAction }
