<?php

namespace Proxies\__CG__\Sportimimi\userBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \Sportimimi\userBundle\Entity\Message implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Message' . "\0" . 'profile_send', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Message' . "\0" . 'profile_recieve', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Message' . "\0" . 'message_reply', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Message' . "\0" . 'created');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Message' . "\0" . 'profile_send', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Message' . "\0" . 'profile_recieve', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Message' . "\0" . 'message_reply', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Message' . "\0" . 'created');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Message $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile_send()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile_send', array());

        return parent::getProfile_send();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile_send(\Sportimimi\userBundle\Entity\Profile $profile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile_send', array($profile));

        return parent::setProfile_send($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfile_recieve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfile_recieve', array());

        return parent::getProfile_recieve();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfile_recieve(\Sportimimi\userBundle\Entity\Profile $profile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfile_recieve', array($profile));

        return parent::setProfile_recieve($profile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage_reply()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage_reply', array());

        return parent::getMessage_reply();
    }

}
