<?php

namespace Proxies\__CG__\Sportimimi\userBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \Sportimimi\userBundle\Entity\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'nom', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'nameVn', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'order', 'profile', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'events', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'levels', 'places', 'imgSrc', 'classIcons', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'news', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'teams');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'nom', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'nameVn', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'order', 'profile', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'events', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'levels', 'places', 'imgSrc', 'classIcons', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'news', '' . "\0" . 'Sportimimi\\userBundle\\Entity\\Category' . "\0" . 'teams');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getImgSrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgSrc', array());

        return parent::getImgSrc();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function getNameVn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameVn', array());

        return parent::getNameVn();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function addEvent(\Sportimimi\userBundle\Entity\Event $event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvent', array($event));

        return parent::addEvent($event);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevels', array());

        return parent::getLevels();
    }

    /**
     * {@inheritDoc}
     */
    public function getClassIcons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassIcons', array());

        return parent::getClassIcons();
    }

    /**
     * {@inheritDoc}
     */
    public function getTeams()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeams', array());

        return parent::getTeams();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfiles', array());

        return parent::getProfiles();
    }

    /**
     * {@inheritDoc}
     */
    public function getEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvents', array());

        return parent::getEvents();
    }

}
