users : 
  type: rest
  resource:     "SportimimiuserBundle:UserRest"
  name_prefix:  api_
  requirements:
    text: .+
news:
  type: rest
  resource: "SportimimiuserBundle:NewsRest"
  name_prefix:  api_
profiles:
  type: rest
  resource: "SportimimiuserBundle:ProfilesRest"
  name_prefix:  api_
notifications:
  type: rest
  resource: "SportimimiuserBundle:NotificationsRest"
  name_prefix:  api_
places:
  type: rest
  resource: "SportimimiuserBundle:PlaceRest"
  name_prefix:  api_