users:
    type: rest
    resource:     "SportimimiuserBundle:UserRest"
    name_prefix:  api_
    requirements:
      text: .+

comments:
    type:     rest
    parent:   users
    resource: Sportimimi\userBundle\Controller\Rest\UserCommentsController
    name_prefix: api_

news:
    type: rest
    resource: "SportimimiuserBundle:NewsRest"
    name_prefix:  api_

profiles:
    type: rest
    resource: "SportimimiuserBundle:ProfilesRest"
    name_prefix:  api_

notifications:
    type: rest
    resource: "SportimimiuserBundle:NotificationsRest"
    name_prefix:  api_

places:
    type: rest
    resource: "SportimimiuserBundle:PlaceRest"
    name_prefix:  api_